name: Makefile CI

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: compilation
      run: make
      
    - name: sandbox compilation
      run: cd sandbox && make
