name: Makefile CI

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Update
      run: sudo apt update

    - name: Checkout submodules
      run: git submodule update --init --recursive

    - name: Install dependencies
      run: sudo apt install -y build-essential cmake ninja-build

    - name: Generate Ninja for mfGUI
      run: cd mfGUI && cmake -B . -H . -G Ninja && cd ..

    - name: compilation
      run: make
      
    - name: sandbox compilation
      run: cd sandbox && make
