name: CMake Ninja CI

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Update package lists
      run: sudo apt update

    - name: Checkout submodules
      run: git submodule update --init --recursive

    - name: Install dependencies
      run: sudo apt install -y build-essential cmake ninja-build libsfml-dev libboost-container-dev

    - name: Set SFML_DIR environment variable
      run: echo "SFML_DIR=/usr/lib/cmake/SFML" >> $GITHUB_ENV

    - name: Build mfGUI library
      run: |
        cd mfGUI
        cmake . -G Ninja -DCMAKE_BUILD_TYPE=Debug
        ninja

    - name: Build Yuna library
      run: |
        cmake . -G Ninja -DCMAKE_BUILD_TYPE=Debug
        ninja

    - name: Build Sandbox
      run: |
        cd sandbox
        cmake . -G Ninja -DCMAKE_BUILD_TYPE=Debug
        ninja
