name: Makefile CI

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: remove git-lfs
        shell: bash
        run: |
          cat /etc/apt/sources.list
          ls /etc/apt/sources.list.d
          sudo rm /etc/apt/sources.list.d/github_git-lfs.list
          sudo rm /etc/apt/sources.list.d/github_git-lfs.list.save


    - name: Checkout submodules
      run: git submodule update --init --recursive

    - name: compilation
      run: make
      
    - name: sandbox compilation
      run: cd sandbox && make
